language: python
python:
  - '2.7'

before_install:
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - export PHANTOMJS_EXECUTABLE=`pwd`/phantomjs
  - git clone git://github.com/n1k0/casperjs.git casperjs
  - export PATH=`pwd`/casperjs/bin/:$PATH

before_script:
  - ./phantomjs --version
  - phantomjs --version
  - casperjs --version
  - python -m SimpleHTTPServer 8080 &
  - sleep 10

script:
  - casperjs test test/integration